services:
  django:
    build: .
    command: python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi --bind  0.0.0.0:8000
    volumes:
      - ./core:/app
    expose:
      - "8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: db
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    
  front:
    build:
      context: .
      dockerfile: dockerfile.front
    volumes:
      - ./front/alzahra-archive:/app
      - /app/node_modules
    ports:
    - "80:80"
    
    depends_on:
      - db
      - django
