# Generated by Django 4.2 on 2024-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Output",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("released_year", models.CharField(max_length=4)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="output/images"),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="output")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
