# Generated by Django 4.2 on 2024-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("final_output", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
