# Generated by Django 4.2 on 2024-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("final_output", "0002_output_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="output",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
