# Generated by Django 4.2 on 2024-09-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("final_output", "0003_alter_output_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="output",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
