# Generated by Django 4.2 on 2024-10-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("final_output", "0004_alter_output_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="output",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="output/files"),
        ),
    ]
