# Generated by Django 4.2 on 2024-08-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="description",
            field=models.TextField(default="some desc"),
        ),
    ]
