# Generated by Django 4.2 on 2024-08-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="archive",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="template/media"),
        ),
    ]
