# Generated by Django 4.2 on 2024-08-30 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="added_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="description",
            field=models.TextField(),
        ),
    ]
